codeunit 50000 "RDLTableBuilder"
{
    Subtype = Test;
    [Test]
    procedure GetReportLayoutXML()
    var
        LayoutXML: XmlDocument;
        XmlNsMgr: XmlNamespaceManager;
        DataSetExportHelper: Codeunit DataSetExportHelper;
        RDLCInnerBody: XmlNode;
    begin
        FindReportRDLCLayout(Report::"Sales - Shipment", LayoutXML);
        DataSetExportHelper.AddNamespaces(XmlNsMgr, LayoutXML);
        LayoutXML.SelectSingleNode('/ns:Report/ns:ReportSections/ns:ReportSectionns:/ns:Body/ns:ReportItems', XMLNsMgr, RDLCInnerBody);
    end;

    local procedure GetReportBodyHeader() HeaderXMLText: Text
    var
        TB: TextBuilder;
    begin
        TB.AppendLine('          <Tablix Name="DataSetTable">');
        TB.AppendLine('            <TablixBody>');
        TB.AppendLine('              <!--Title Line-->');
        TB.AppendLine('              <TablixColumns>');
        TB.AppendLine('                <TablixColumn>');
        TB.AppendLine('                  <Width>2.5cm</Width>');
        TB.AppendLine('                </TablixColumn>');
        TB.AppendLine('                <TablixColumn>');
        TB.AppendLine('                  <Width>2.5cm</Width>');
        TB.AppendLine('                </TablixColumn>');
        TB.AppendLine('                <TablixColumn>');
        TB.AppendLine('                  <Width>2.5cm</Width>');
        TB.AppendLine('                </TablixColumn>');
        TB.AppendLine('              </TablixColumns>');
        TB.AppendLine('              <TablixRows>');
        TB.AppendLine('                <TablixRow>');
        TB.AppendLine('                  <Height>0.6cm</Height>');
        TB.AppendLine('                  <TablixCells>');
        TB.AppendLine('                   <!--Fields-->');
        TB.AppendLine('                    <TablixCell>');
        TB.AppendLine('                      <CellContents>');
        TB.AppendLine('                        <Textbox Name="Textbox1">');
        TB.AppendLine('                          <CanGrow>true</CanGrow>');
        TB.AppendLine('                          <KeepTogether>true</KeepTogether>');
        TB.AppendLine('                          <Paragraphs>');
        TB.AppendLine('                            <Paragraph>');
        TB.AppendLine('                              <TextRuns>');
        TB.AppendLine('                                <TextRun>');
        TB.AppendLine('                                  <Value>Spalte 1</Value>');
        TB.AppendLine('                                  <Style />');
        TB.AppendLine('                                </TextRun>');
        TB.AppendLine('                              </TextRuns>');
        TB.AppendLine('                              <Style />');
        TB.AppendLine('                            </Paragraph>');
        TB.AppendLine('                          </Paragraphs>');
        TB.AppendLine('                          <rd:DefaultName>Textbox1</rd:DefaultName>');
        TB.AppendLine('                          <Style>');
        TB.AppendLine('                            <Border>');
        TB.AppendLine('                              <Color>LightGrey</Color>');
        TB.AppendLine('                              <Style>Solid</Style>');
        TB.AppendLine('                            </Border>');
        TB.AppendLine('                            <PaddingLeft>2pt</PaddingLeft>');
        TB.AppendLine('                            <PaddingRight>2pt</PaddingRight>');
        TB.AppendLine('                            <PaddingTop>2pt</PaddingTop>');
        TB.AppendLine('                            <PaddingBottom>2pt</PaddingBottom>');
        TB.AppendLine('                          </Style>');
        TB.AppendLine('                        </Textbox>');
        TB.AppendLine('                      </CellContents>');
        TB.AppendLine('                    </TablixCell>');
        TB.AppendLine('                    <TablixCell>');
        TB.AppendLine('                      <CellContents>');
        TB.AppendLine('                        <Textbox Name="Textbox3">');
        TB.AppendLine('                          <CanGrow>true</CanGrow>');
        TB.AppendLine('                          <KeepTogether>true</KeepTogether>');
        TB.AppendLine('                          <Paragraphs>');
        TB.AppendLine('                            <Paragraph>');
        TB.AppendLine('                              <TextRuns>');
        TB.AppendLine('                                <TextRun>');
        TB.AppendLine('                                  <Value>Spalte 2</Value>');
        TB.AppendLine('                                  <Style />');
        TB.AppendLine('                                </TextRun>');
        TB.AppendLine('                              </TextRuns>');
        TB.AppendLine('                              <Style />');
        TB.AppendLine('                            </Paragraph>');
        TB.AppendLine('                          </Paragraphs>');
        TB.AppendLine('                          <rd:DefaultName>Textbox3</rd:DefaultName>');
        TB.AppendLine('                          <Style>');
        TB.AppendLine('                            <Border>');
        TB.AppendLine('                              <Color>LightGrey</Color>');
        TB.AppendLine('                              <Style>Solid</Style>');
        TB.AppendLine('                            </Border>');
        TB.AppendLine('                            <PaddingLeft>2pt</PaddingLeft>');
        TB.AppendLine('                            <PaddingRight>2pt</PaddingRight>');
        TB.AppendLine('                            <PaddingTop>2pt</PaddingTop>');
        TB.AppendLine('                            <PaddingBottom>2pt</PaddingBottom>');
        TB.AppendLine('                          </Style>');
        TB.AppendLine('                        </Textbox>');
        TB.AppendLine('                      </CellContents>');
        TB.AppendLine('                    </TablixCell>');
        TB.AppendLine('                    <TablixCell>');
        TB.AppendLine('                      <CellContents>');
        TB.AppendLine('                        <Textbox Name="Textbox5">');
        TB.AppendLine('                          <CanGrow>true</CanGrow>');
        TB.AppendLine('                          <KeepTogether>true</KeepTogether>');
        TB.AppendLine('                          <Paragraphs>');
        TB.AppendLine('                            <Paragraph>');
        TB.AppendLine('                              <TextRuns>');
        TB.AppendLine('                                <TextRun>');
        TB.AppendLine('                                  <Value>Spalte 3</Value>');
        TB.AppendLine('                                  <Style />');
        TB.AppendLine('                                </TextRun>');
        TB.AppendLine('                              </TextRuns>');
        TB.AppendLine('                              <Style />');
        TB.AppendLine('                            </Paragraph>');
        TB.AppendLine('                          </Paragraphs>');
        TB.AppendLine('                          <rd:DefaultName>Textbox5</rd:DefaultName>');
        TB.AppendLine('                          <Style>');
        TB.AppendLine('                            <Border>');
        TB.AppendLine('                              <Color>LightGrey</Color>');
        TB.AppendLine('                              <Style>Solid</Style>');
        TB.AppendLine('                            </Border>');
        TB.AppendLine('                            <PaddingLeft>2pt</PaddingLeft>');
        TB.AppendLine('                            <PaddingRight>2pt</PaddingRight>');
        TB.AppendLine('                            <PaddingTop>2pt</PaddingTop>');
        TB.AppendLine('                            <PaddingBottom>2pt</PaddingBottom>');
        TB.AppendLine('                          </Style>');
        TB.AppendLine('                        </Textbox>');
        TB.AppendLine('                      </CellContents>');
        TB.AppendLine('                    </TablixCell>');
        TB.AppendLine('                  </TablixCells>');
        TB.AppendLine('                </TablixRow>');
        TB.AppendLine('                <TablixRow>');
        TB.AppendLine('                  <Height>0.6cm</Height>');
        TB.AppendLine('                  <TablixCells>');
        TB.AppendLine('                    <TablixCell>');
        TB.AppendLine('                      <CellContents>');
        TB.AppendLine('                        <Textbox Name="No_">');
        TB.AppendLine('                          <CanGrow>true</CanGrow>');
        TB.AppendLine('                          <KeepTogether>true</KeepTogether>');
        TB.AppendLine('                          <Paragraphs>');
        TB.AppendLine('                            <Paragraph>');
        TB.AppendLine('                              <TextRuns>');
        TB.AppendLine('                                <TextRun>');
        TB.AppendLine('                                  <Value>=Fields!No_.Value</Value>');
        TB.AppendLine('                                  <Style />');
        TB.AppendLine('                                </TextRun>');
        TB.AppendLine('                              </TextRuns>');
        TB.AppendLine('                              <Style />');
        TB.AppendLine('                            </Paragraph>');
        TB.AppendLine('                          </Paragraphs>');
        TB.AppendLine('                          <rd:DefaultName>No_</rd:DefaultName>');
        TB.AppendLine('                          <Style>');
        TB.AppendLine('                            <Border>');
        TB.AppendLine('                              <Color>LightGrey</Color>');
        TB.AppendLine('                              <Style>Solid</Style>');
        TB.AppendLine('                            </Border>');
        TB.AppendLine('                            <PaddingLeft>2pt</PaddingLeft>');
        TB.AppendLine('                            <PaddingRight>2pt</PaddingRight>');
        TB.AppendLine('                            <PaddingTop>2pt</PaddingTop>');
        TB.AppendLine('                            <PaddingBottom>2pt</PaddingBottom>');
        TB.AppendLine('                          </Style>');
        TB.AppendLine('                        </Textbox>');
        TB.AppendLine('                      </CellContents>');
        TB.AppendLine('                    </TablixCell>');
        TB.AppendLine('                    <TablixCell>');
        TB.AppendLine('                      <CellContents>');
        TB.AppendLine('                        <Textbox Name="Type">');
        TB.AppendLine('                          <CanGrow>true</CanGrow>');
        TB.AppendLine('                          <KeepTogether>true</KeepTogether>');
        TB.AppendLine('                          <Paragraphs>');
        TB.AppendLine('                            <Paragraph>');
        TB.AppendLine('                              <TextRuns>');
        TB.AppendLine('                                <TextRun>');
        TB.AppendLine('                                  <Value>=Fields!Type.Value</Value>');
        TB.AppendLine('                                  <Style />');
        TB.AppendLine('                                </TextRun>');
        TB.AppendLine('                              </TextRuns>');
        TB.AppendLine('                              <Style />');
        TB.AppendLine('                            </Paragraph>');
        TB.AppendLine('                          </Paragraphs>');
        TB.AppendLine('                          <rd:DefaultName>Type</rd:DefaultName>');
        TB.AppendLine('                          <Style>');
        TB.AppendLine('                            <Border>');
        TB.AppendLine('                              <Color>LightGrey</Color>');
        TB.AppendLine('                              <Style>Solid</Style>');
        TB.AppendLine('                            </Border>');
        TB.AppendLine('                            <PaddingLeft>2pt</PaddingLeft>');
        TB.AppendLine('                            <PaddingRight>2pt</PaddingRight>');
        TB.AppendLine('                            <PaddingTop>2pt</PaddingTop>');
        TB.AppendLine('                            <PaddingBottom>2pt</PaddingBottom>');
        TB.AppendLine('                          </Style>');
        TB.AppendLine('                        </Textbox>');
        TB.AppendLine('                      </CellContents>');
        TB.AppendLine('                    </TablixCell>');
        TB.AppendLine('                    <TablixCell>');
        TB.AppendLine('                      <CellContents>');
        TB.AppendLine('                        <Textbox Name="Description">');
        TB.AppendLine('                          <CanGrow>true</CanGrow>');
        TB.AppendLine('                          <KeepTogether>true</KeepTogether>');
        TB.AppendLine('                          <Paragraphs>');
        TB.AppendLine('                            <Paragraph>');
        TB.AppendLine('                              <TextRuns>');
        TB.AppendLine('                                <TextRun>');
        TB.AppendLine('                                  <Value>=Fields!Description.Value</Value>');
        TB.AppendLine('                                  <Style />');
        TB.AppendLine('                                </TextRun>');
        TB.AppendLine('                              </TextRuns>');
        TB.AppendLine('                              <Style />');
        TB.AppendLine('                            </Paragraph>');
        TB.AppendLine('                          </Paragraphs>');
        TB.AppendLine('                          <rd:DefaultName>Description</rd:DefaultName>');
        TB.AppendLine('                          <Style>');
        TB.AppendLine('                            <Border>');
        TB.AppendLine('                              <Color>LightGrey</Color>');
        TB.AppendLine('                              <Style>Solid</Style>');
        TB.AppendLine('                            </Border>');
        TB.AppendLine('                            <PaddingLeft>2pt</PaddingLeft>');
        TB.AppendLine('                            <PaddingRight>2pt</PaddingRight>');
        TB.AppendLine('                            <PaddingTop>2pt</PaddingTop>');
        TB.AppendLine('                            <PaddingBottom>2pt</PaddingBottom>');
        TB.AppendLine('                          </Style>');
        TB.AppendLine('                        </Textbox>');
        TB.AppendLine('                      </CellContents>');
        TB.AppendLine('                    </TablixCell>');
        TB.AppendLine('                  </TablixCells>');
        TB.AppendLine('                </TablixRow>');
        TB.AppendLine('              </TablixRows>');
        TB.AppendLine('            </TablixBody>');
        TB.AppendLine('            <TablixColumnHierarchy>');
        TB.AppendLine('              <TablixMembers>');
        TB.AppendLine('                <TablixMember />');
        TB.AppendLine('                <TablixMember />');
        TB.AppendLine('                <TablixMember />');
        TB.AppendLine('              </TablixMembers>');
        TB.AppendLine('            </TablixColumnHierarchy>');
        TB.AppendLine('            <TablixRowHierarchy>');
        TB.AppendLine('              <TablixMembers>');
        TB.AppendLine('                <TablixMember>');
        TB.AppendLine('                  <KeepWithGroup>After</KeepWithGroup>');
        TB.AppendLine('                </TablixMember>');
        TB.AppendLine('                <TablixMember>');
        TB.AppendLine('                  <Group Name="Details" />');
        TB.AppendLine('                </TablixMember>');
        TB.AppendLine('              </TablixMembers>');
        TB.AppendLine('            </TablixRowHierarchy>');
        TB.AppendLine('            <DataSetName>DataSet_Result</DataSetName>');
        TB.AppendLine('            <Height>1.2cm</Height>');
        TB.AppendLine('            <Width>7.5cm</Width>');
        TB.AppendLine('            <Style>');
        TB.AppendLine('              <Border>');
        TB.AppendLine('                <Style>None</Style>');
        TB.AppendLine('              </Border>');
        TB.AppendLine('            </Style>');
        TB.AppendLine('          </Tablix>');
        TB.AppendLine('        </ReportItems>');
        TB.AppendLine('        <Height>5.08cm</Height>');
        TB.AppendLine('        <Style />');
        TB.AppendLine('      </Body>');
        TB.AppendLine('      <Width>16.51cm</Width>');
        TB.AppendLine('      <Page>');
        TB.AppendLine('        <PageHeight>21.59cm</PageHeight>');
        TB.AppendLine('        <PageWidth>27.94cm</PageWidth>');
        TB.AppendLine('        <LeftMargin>0cm</LeftMargin>');
        TB.AppendLine('        <RightMargin>0cm</RightMargin>');
        TB.AppendLine('        <TopMargin>0cm</TopMargin>');
        TB.AppendLine('        <BottomMargin>0cm</BottomMargin>');
        TB.AppendLine('        <ColumnSpacing>1.27cm</ColumnSpacing>');
        TB.AppendLine('        <Style />');
        TB.AppendLine('      </Page>');
        TB.AppendLine('    </ReportSection>');
        TB.AppendLine('  </ReportSections>');
        TB.AppendLine('  <ReportParametersLayout>');
        TB.AppendLine('    <GridLayoutDefinition>');
        TB.AppendLine('      <NumberOfColumns>4</NumberOfColumns>');
        TB.AppendLine('      <NumberOfRows>2</NumberOfRows>');
        TB.AppendLine('    </GridLayoutDefinition>');
        TB.AppendLine('  </ReportParametersLayout>');
        TB.AppendLine('  <Language>=User!Language</Language>');
        TB.AppendLine('  <ConsumeContainerWhitespace>true</ConsumeContainerWhitespace>');
        TB.AppendLine('  <rd:ReportUnitType>Cm</rd:ReportUnitType>');
        TB.AppendLine('  <rd:ReportID>0eeb6585-38ae-40f1-885b-8d50088d51b4</rd:ReportID>');
        TB.AppendLine('</Report>');
    end;

    local procedure FindReportRDLCLayout(ReportID: Integer; var LayoutXML: XmlDocument) Found: Boolean
    var
        LayoutInstream: InStream;
    begin
        if not Report.RdlcLayout(ReportID, LayoutInstream) then
            exit(false);
        Found := XmlDocument.ReadFrom(LayoutInstream, LayoutXML);
    end;
}